from typing import Protocol

from typing_extensions import Self

class SupportsFloatDivMul(Protocol):
    def __truediv__(self, other: float | Self) -> Self: ...
    def __rtruediv__(self, other: float | Self) -> Self: ...
    def __mul__(self, other: float | Self) -> Self: ...
    def __rmul__(self, other: float | Self) -> Self: ...
